package helpers

import (
	"context"
	"log"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

// GenerateParagraphs is a function that will be called to generate paragraphs using the Gemini API.
func GenerateParagraphs() ([]string, error) {
	// Context must be created inside a function, not at the package level
	ctx := context.Background()

	// Initialize the client with the API key from the environment variables
	client, err := genai.NewClient(ctx, option.WithAPIKey(os.Getenv("API_KEY")))
	if err != nil {
		log.Fatal(err)
		return nil, err
	}
	defer client.Close()

	// Placeholder for actual API call to generate paragraphs
	paragraphs := []string{
		"First generated paragraph",
		"Second generated paragraph",
		// Add more paragraphs as generated by the API
	}

	return paragraphs, nil
}
